# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- feature/*

pool:
  vmImage: 'macos-latest'

steps:
- task: DownloadSecureFile@1
  displayName: 'App Distribution用のクレデンシャルを取得'
  name: deployUserCredential
  inputs:
    secureFile: nyannyanengine-android-deploy-user.json
- task: DownloadSecureFile@1
  displayName: 'ビルド用のクレデンシャルを取得'
  name: appKeyProperties
  inputs:
    secureFile: app_gradle_secret.properties
- script: |
    sudo ln -s $(appKeyProperties.secureFilePath) app/gradle_secret.properties
  displayName: 'ビルド用クレデンシャルをプロジェクト内部に設置'
- task: Gradle@2
  displayName: '全環境に対してlint'
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'lint'
- task: Gradle@2
  displayName: 'Debug環境でビルド'
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'
- script: |
    sudo ln -s $(deployUserCredential.secureFilePath) app/android-deploy-user.json
  displayName: 'App Distribution用クレデンシャルをプロジェクト内部に設置'
- task: Gradle@2
  displayName: 'Releaseビルドを配布'
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease appDistributionUploadRelease'
